//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace MigrationTool
{
// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class AssemblyList {
    
        private AssemblyListAssembly[] assemblyField;
    
        /// <remarks/>
        [XmlElement("Assembly")]
        public AssemblyListAssembly[] Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class AssemblyListAssembly {
    
        private string appNameField;
    
        private string asmNameField;
    
        private string asmVerField;
    
        /// <remarks/>
        [XmlAttribute()]
        public string AppName {
            get {
                return this.appNameField;
            }
            set {
                this.appNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string AsmName {
            get {
                return this.asmNameField;
            }
            set {
                this.asmNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string AsmVer {
            get {
                return this.asmVerField;
            }
            set {
                this.asmVerField = value;
            }
        }
    }
}