//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


namespace MigrationTool
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Servers {
    
        private string srcSqlInstanceField;
        private string srcNodesField;
        private string dstSqlInstanceField;
        private string dstNodesField;
        private string srcAppNodeField;
        private string dstAppNodeField;
        /// <remarks/>
        public string SrcSqlInstance {
            get {
                return this.srcSqlInstanceField;
            }
            set {
                this.srcSqlInstanceField = value;
            }
        }
        public string SrcNodes
        {
            get
            {
                return this.srcNodesField;
            }
            set
            {
                this.srcNodesField = value;
            }
        }    
        /// <remarks/>    

        public string DstSqlInstance
        {
            get
            {
                return this.dstSqlInstanceField;
            }
            set
            {
                this.dstSqlInstanceField = value;
            }
        }

        public string DstNodes
        {
            get
            {
                return this.dstNodesField;
            }
            set
            {
                this.dstNodesField = value;
            }
        }

        public string DstAppNode
        {
            get
            {
                return this.dstAppNodeField;
            }
            set
            {
                this.dstAppNodeField = value;
            }
        }

        public string SrcAppNode
        {
            get
            {
                return this.srcAppNodeField;
            }
            set
            {
                this.srcAppNodeField = value;
            }
        }
    }
}
