//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace RemoteOperations
{
// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class BizTalkApplications {
    
        private BizTalkApplicationsBizTalkApplication[] bizTalkApplicationField;
    
        /// <remarks/>
        [XmlElement("BizTalkApplication")]
        public BizTalkApplicationsBizTalkApplication[] BizTalkApplication {
            get {
                return this.bizTalkApplicationField;
            }
            set {
                this.bizTalkApplicationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class BizTalkApplicationsBizTalkApplication {
    
        private string dependencyCodeField;
    
        private string applicationNameField;
    
        /// <remarks/>
        [XmlAttribute()]
        public string DependencyCode {
            get {
                return this.dependencyCodeField;
            }
            set {
                this.dependencyCodeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
    }
}